[package]
name = "runner-nix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
hyper = { version = "0.14", features = ["full"] }
systemd = "0.10.0"
tokio = { version = "1.20.1", features = ["full"] }
